♻️ weather 기능 리팩토링
kakao-tech-bootcamp-17th/chatbot-server pull request #12
Opened 2024-08-26 09:16 UTC by alreadysons

#8 리팩토링 과정입니다

1. 기존의 weather_service 삭제 
2. weather_api의 기능을 weather_service로 리팩토링
3. 내부변수의 URL 변경

---추후 할 것---
1. API 외부 호출
2. DTO

2024-08-26 15:13 UTC, swandevson requested changes
LGTM
리뷰 한 번 확인해주세용

2024-08-26 15:13 UTC, swandevson commented on app/weather/weather_service.py
> +            raise ValueError("OPENWEATHER_API_KEY is not set in environment variables")
config의 변수명과 다릅니다(오타)

2024-08-27 05:14 UTC, alreadysons commented on app/weather/weather_service.py
> +            raise ValueError("OPENWEATHER_API_KEY is not set in environment variables")
config는 제가 건든적이 없는데 혹시 달라진게 있을까요..??

2024-08-27 05:26 UTC, swandevson commented on app/weather/weather_service.py
> +            raise ValueError("OPENWEATHER_API_KEY is not set in environment variables")
valueError 부분 말씀드린겁니다

2024-08-27 05:31 UTC, swandevson requested changes
리뷰 확인 부탁드립니다!

2024-08-27 05:31 UTC, swandevson commented on app/external_api/weather_api.py
> +            raise ValueError("OPENWEATHER_API_KEY is not set in environment variables")
`OPEN_WEATHER`인지 `OPENWEATHER`인지 통일시켜주세요
config에서 `OPEN_WEATHER`를 먼저 썼으니 띄어쓰는게 좋겠죠?

2024-08-27 05:31 UTC, swandevson commented on app/weather/weather_service.py
> +        result = self.api_client.fetch_weather_data(lat, lon)
내부에서 호출하는 함수가 `fetch_weather_data`면 해당 함수면도 `get_weather_data` 혹은 `get_weather_info`가 좋지 않을까요?
`get_weather`만으로는 날씨의 뭘 갖고 오겠다는 것인지 잘 파악되지 않을 것 같습니다

2024-08-27 05:31 UTC, swandevson commented on app/weather/weather_service.py
> +        self.api_client = WeatherApi()
네이밍을 `api_client`로 하신 이유가 있으실까요?

2024-08-27 05:47 UTC, alreadysons commented on app/weather/weather_service.py
> +        self.api_client = WeatherApi()
weather 어플리케이션 내부에서 api를 불러온다는 뜻에서 네이밍을 지었습니다 혹시 헷갈리시면 다른 네이밍으로 하는게 좋을까요?

2024-08-27 05:47 UTC, alreadysons commented on app/weather/weather_service.py
> +        result = self.api_client.fetch_weather_data(lat, lon)
get_weather_info가 좋은것 같습니다! 수정하겠습니다.

2024-08-27 05:47 UTC, alreadysons commented on app/external_api/weather_api.py
> +            raise ValueError("OPENWEATHER_API_KEY is not set in environment variables")
아하 인지했습니다!

2024-08-27 06:42 UTC, swandevson approved these changes
LGTM

2024-08-27 08:05 UTC, swandevson requested changes
리뷰 확인 부탁드립니다

2024-08-27 08:05 UTC, swandevson commented on app/local/local_service.py
> +            self.KakaoLocalCoordinateApi = KakaoLocalApi()
왼쪽 변수명도 변경되어야하지 않나요?

2024-08-27 08:05 UTC, swandevson commented on app/local/local_service.py
>          result = self.KakaoLocalCoordinateApi.get_coordinates(address)
해당 함수명은 `coordinates_info`, 내부에서 호출하는 함수는 `coordinates`만 써서 통일성이 깨집니다.
서로 다른 서비스이기때문에 네이밍이 무조건 달라야할 이유는 없습니다
이런 부분은 누차 말씀드리지만 통일해주시길 바랍니다!

2024-08-27 08:38 UTC, alreadysons commented on app/local/local_service.py
> +            self.KakaoLocalCoordinateApi = KakaoLocalApi()
엇 체킹 못했네요 수정하겠습니당

2024-08-27 08:44 UTC, alreadysons commented on app/local/local_service.py
>          result = self.KakaoLocalCoordinateApi.get_coordinates(address)
넵!

2024-08-27 09:16 UTC, merged

2024-08-27 22:35 UTC, swandevson commented on app/local/local_route.py
> +    coordinates_info = local_service.get_coordinates(address)
직전 리뷰 달아드렸던 내용인데, 함수에서 return되는 값 이름이랑 변수명이 달라 통일성이 깨집니다...
커밋 전에 스테이징 되는 내용들 한 번 꼭 확인해주세요...