✨ get_weather_by_address 기능 생성
kakao-tech-bootcamp-17th/chatbot-server pull request #20
Opened 2024-08-29 07:33 UTC by alreadysons

#15 
get_weather_by_address라는 네이밍으로 일단 주소명을 입력받아 weather에 넘겨 정보를 받아와 출력하는 기능을 생성하였습니다.

추후 진행해야할 논제

1. get_weather_by_address의 마땅한 네이밍 짓기
2. get_weather_by_address의 라우트 네이밍 짓기
3. get_weather_by_address의 반환값 설정 -> 현재는 주소, 좌표, 날씨정보를 딕셔너리 형태로 출력

2024-08-29 07:45 UTC, swandevson requested changes
리뷰 확인해주세용

2024-08-29 07:45 UTC, swandevson commented on app/local/local_route.py
> +    return local_service.get_weather_by_address(address)
날씨면 `local` 도메인이 아니라 `weather` 도메인에 있는게 올바를 것 같습니다
서비스 또한 `local`이 아닌 `weather`가 올바를 것 같습니다

2024-08-29 07:50 UTC, alreadysons commented on app/local/local_route.py
> +    return local_service.get_weather_by_address(address)
weather로 옮기게 되면 네이밍은 그대로 가도 될것같은데 혹시 이점은 어떻게 생각하시나요?

2024-08-29 08:28 UTC, alreadysons commented on app/weather/weather_route.py
> +@weather_bp.route("/weather-by-address", methods=['GET'])
라우트명을 다음과 같이 정했습니다

2024-08-29 08:59 UTC, swandevson commented on app/weather/weather_route.py
> +@weather_bp.route("/weather-by-address", methods=['GET'])
리소스명이라기엔 메소드이름같이 동사 느낌이 너무 강합니다.
그리고 prefix로 weather가 이미 있는데 다시 쓸 이유는 없습니다

2024-08-29 09:00 UTC, swandevson commented on app/weather/weather_route.py
> +@weather_bp.route("/weather-by-address", methods=['GET'])
https://prohannah.tistory.com/156
참고바랍니다.

2024-09-02 08:37 UTC, swandevson approved these changes
LGTM

2024-09-02 08:37 UTC, swandevson requested changes
TEST

2024-09-02 09:00 UTC, merged